[project]
org-name = "ballerinax"
version = "0.99.1"
authors = ["Ballerina"]
keywords = ["github", "endpoint", "API"]
repository = "https://github.com/ballerina-platform/module-github"
license = ["Apache-2.0"]
