[project]
org-name = "ballerinax"
version = "0.10.0"
authors = ["WSO2"]
keywords = ["github", "endpoint", "API"]
repository = "https://github.com/ballerina-platform/module-github"
license = ["Apache-2.0"]
