name: Pull Request

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        # tests will be skipped if the PR is from a forked repository (as the secrets are not available)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: bal test ./ballerina --test-report --code-coverage --coverage-format=xml
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          USER_REPO_NAME: ${{ secrets.REPO_NAME }}
          ISSUE_ASSIGNEE: ${{ secrets.ASSIGNEE }}
          RESOURCE_PATH: ${{ secrets.RESOURCE_PATH }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GITHUB_USERNAME: ${{ secrets.USERNAME }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
