name: Deployment

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            pack ./github
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          USER_REPO_NAME: ${{ secrets.REPO_NAME }}
          ISSUE_ASSIGNEE: ${{ secrets.ASSIGNEE }}
          RESOURCE_PATH: ${{ secrets.RESOURCE_PATH }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GITHUB_USERNAME: ${{ secrets.USERNAME }}

      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            push
        env:
          WORKING_DIR: ./github
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}

